name: wasmer deploy
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  wasmer-deploy:
    permissions:
      contents: write
    environment:
      name: wasmer
      url: https://jcbhmr-hello-world-rust-wasmer-app.wasmer.app/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wasmerio/setup-wasmer@v3
      - run: rustup target add wasm32-wasi
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-wasix
      - run: cargo wasix build --release
      - run: wasmer deploy --publish-package
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
      - uses: actions4git/add-commit-push@v1
